
# This file is automatically generated, you probably don't want to edit this

plotOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            xvar = NULL,
            yvar = NULL,
            group = NULL,
            type = "point",
            xlab = "x",
            ylab = "y", ...) {

            super$initialize(
                package="jjplot",
                name="plot",
                requiresData=TRUE,
                ...)

            private$..xvar <- jmvcore::OptionVariable$new(
                "xvar",
                xvar)
            private$..yvar <- jmvcore::OptionVariable$new(
                "yvar",
                yvar)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..type <- jmvcore::OptionList$new(
                "type",
                type,
                options=list(
                    "point",
                    "line",
                    "boxplot"),
                default="point")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="x")
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="y")

            self$.addOption(private$..xvar)
            self$.addOption(private$..yvar)
            self$.addOption(private$..group)
            self$.addOption(private$..type)
            self$.addOption(private$..xlab)
            self$.addOption(private$..ylab)
        }),
    active = list(
        xvar = function() private$..xvar$value,
        yvar = function() private$..yvar$value,
        group = function() private$..group$value,
        type = function() private$..type$value,
        xlab = function() private$..xlab$value,
        ylab = function() private$..ylab$value),
    private = list(
        ..xvar = NA,
        ..yvar = NA,
        ..group = NA,
        ..type = NA,
        ..xlab = NA,
        ..ylab = NA)
)

plotResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotResults",
    inherit = jmvcore::Group,
    active = list(
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Exploratory plot")
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Exploratory plot",
                width=400,
                height=300,
                renderFun=".plot"))}))

plotBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "plotBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jjplot",
                name = "plot",
                version = c(1,0,0),
                options = options,
                results = plotResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Exploratory plot
#'
#' 
#' @param data .
#' @param xvar .
#' @param yvar .
#' @param group .
#' @param type .
#' @param xlab .
#' @param ylab .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
plot <- function(
    data,
    xvar,
    yvar,
    group,
    type = "point",
    xlab = "x",
    ylab = "y") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("plot requires jmvcore to be installed (restart may be required)")

    if ( ! missing(xvar)) xvar <- jmvcore::resolveQuo(jmvcore::enquo(xvar))
    if ( ! missing(yvar)) yvar <- jmvcore::resolveQuo(jmvcore::enquo(yvar))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(xvar), xvar, NULL),
            `if`( ! missing(yvar), yvar, NULL),
            `if`( ! missing(group), group, NULL))


    options <- plotOptions$new(
        xvar = xvar,
        yvar = yvar,
        group = group,
        type = type,
        xlab = xlab,
        ylab = ylab)

    analysis <- plotClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

